<a href="https://colab.research.google.com/github/AfifNurraihan/Prediction_Method/blob/main/Cat_and_Mouse_Based_Optimization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Optimasi menggunakan CMBO**

## Import Library

In [1]:
import math
import numpy as np
import pandas as pd
from random import randrange

## Inisialisasi Awal

In [2]:
lb         = -100 #Batas Bawah
ub         = 100  #Batas Atas
dm         = 2    #Dimensi
population = 20   #Banyak Search Agent
max_iter   = 100

## Pembentukan Populasi Awal

In [3]:
def generate_agent(lb, ub,size):
  agent = lb + np.random.rand(*size)*(ub-lb)
  return agent

In [4]:
agent = generate_agent(lb,ub,size=(population,dm))
print('Populasi Awal : \n',agent)

Populasi Awal : 
 [[-88.69289956 -24.7372621 ]
 [-83.58758234  11.8158417 ]
 [ 42.79926273  20.89054979]
 [ 88.81365703 -54.02561972]
 [ 56.03385178 -79.76478368]
 [ 23.61220172 -18.95328562]
 [ 16.69093583 -11.91765846]
 [-84.2677153  -73.61590815]
 [-35.12404409  66.14097604]
 [-56.59270918  66.06838973]
 [ 85.66831509  92.48634609]
 [ 89.80026992  -9.54605408]
 [  5.11748842 -39.06503963]
 [-79.87619322 -86.30449681]
 [ 57.86910156 -37.38912793]
 [ 34.05745281  62.96922108]
 [ -0.54472734  66.22596539]
 [ 32.68770462  65.08442085]
 [ 61.84862308 -73.60650598]
 [-95.16652439 -59.72147948]]


## Menghitung Fungsi Objektif pada Populasi Awal

In [5]:
def objective_function(agent):
  # x**2 + x**2
  F_obj = agent[:,0]**2 + agent[:,1]**2
  return F_obj

In [6]:
F_obj = objective_function(agent)
print('Fungsi Objektif : \n',F_obj)

Fungsi Objektif : 
 [ 8478.36256796  7126.4980359   2268.19196059 10806.63326111
  9502.21325981   916.76310571   420.61792202 12520.34977454
  5608.32718506  7567.76685387 15892.78442345  8155.21562645
  1552.26600883 13828.67241185  4746.77980201  5125.0328949
  4386.1752202   5304.4678711   9243.16989976 12623.32247539]


## Urutkan Populasi Awal berdasarkan Fungsi Objektif Terurut

In [7]:
sorted_index = F_obj.argsort()
F_obj        = F_obj[sorted_index]
agent_ori    = agent.copy()
agent        = agent[sorted_index]

In [8]:
agent

array([[ 16.69093583, -11.91765846],
       [ 23.61220172, -18.95328562],
       [  5.11748842, -39.06503963],
       [ 42.79926273,  20.89054979],
       [ -0.54472734,  66.22596539],
       [ 57.86910156, -37.38912793],
       [ 34.05745281,  62.96922108],
       [ 32.68770462,  65.08442085],
       [-35.12404409,  66.14097604],
       [-83.58758234,  11.8158417 ],
       [-56.59270918,  66.06838973],
       [ 89.80026992,  -9.54605408],
       [-88.69289956, -24.7372621 ],
       [ 61.84862308, -73.60650598],
       [ 56.03385178, -79.76478368],
       [ 88.81365703, -54.02561972],
       [-84.2677153 , -73.61590815],
       [-95.16652439, -59.72147948],
       [-79.87619322, -86.30449681],
       [ 85.66831509,  92.48634609]])

In [9]:
F_obj

array([  420.61792202,   916.76310571,  1552.26600883,  2268.19196059,
        4386.1752202 ,  4746.77980201,  5125.0328949 ,  5304.4678711 ,
        5608.32718506,  7126.4980359 ,  7567.76685387,  8155.21562645,
        8478.36256796,  9243.16989976,  9502.21325981, 10806.63326111,
       12520.34977454, 12623.32247539, 13828.67241185, 15892.78442345])

## Improve Pembagian Populasi Tikus dan Kucing

In [10]:
# Improve populasi Tikus 50%, Kucing 50%
pres_mice  = 50                                # Dalam Persen
gen_mice   = round(population*(pres_mice/100)) # Banyaknya populasi tikus

upper_half = slice(gen_mice)
lower_half = slice(gen_mice, len(agent))

In [11]:
#Populasi Tikus
mice_pop = agent[upper_half]
mice_obj = F_obj[upper_half]

#Populasi Kucing
cat_pop = agent[lower_half]
cat_obj = F_obj[lower_half]

print('Populasi Tikus  : \n', mice_pop,'\n')
print('Populasi Kucing : \n', cat_pop,'\n')

Populasi Tikus  : 
 [[ 16.69093583 -11.91765846]
 [ 23.61220172 -18.95328562]
 [  5.11748842 -39.06503963]
 [ 42.79926273  20.89054979]
 [ -0.54472734  66.22596539]
 [ 57.86910156 -37.38912793]
 [ 34.05745281  62.96922108]
 [ 32.68770462  65.08442085]
 [-35.12404409  66.14097604]
 [-83.58758234  11.8158417 ]] 

Populasi Kucing : 
 [[-56.59270918  66.06838973]
 [ 89.80026992  -9.54605408]
 [-88.69289956 -24.7372621 ]
 [ 61.84862308 -73.60650598]
 [ 56.03385178 -79.76478368]
 [ 88.81365703 -54.02561972]
 [-84.2677153  -73.61590815]
 [-95.16652439 -59.72147948]
 [-79.87619322 -86.30449681]
 [ 85.66831509  92.48634609]] 



## Kucing Mengejar Tikus

In [12]:
# Update pergerakan kucing dengan sebarang tikus indeks berbeda
def update_cat_movement(cat_pop, mice_pop):
  random_index = randrange(len(mice_pop))
  I = np.round(1 + np.random.rand(len(cat_pop), dm))
  r = np.random.rand()
  new_pop = cat_pop + r *(mice_pop[random_index] - I * cat_pop)
  return new_pop

In [13]:
cat_pop_move = update_cat_movement(cat_pop, mice_pop)
cat_obj_move = objective_function(cat_pop_move)

print('Populasi Kucing Bergerak : \n',cat_pop_move)
print('\n')
print('Fungsi Objektif Populasi Kucing Bergerak : \n',cat_obj_move)

Populasi Kucing Bergerak : 
 [[-55.63205153  65.34690606]
 [ 89.18573847  -8.64031425]
 [-86.43250773 -23.7707804 ]
 [ 60.86936001 -71.32218467]
 [ 55.78264713 -78.2062056 ]
 [ 88.20974153 -52.16267925]
 [-83.00927447 -72.123492  ]
 [-92.7668201  -58.37856744]
 [-78.66500518 -84.67555139]
 [ 84.17645204  91.19634777]]


Fungsi Objektif Populasi Kucing Bergerak : 
 [ 7365.14328912  8028.75097647  8035.62839354  8791.93301459
  9227.91431494 10501.90360856 12092.33774572 12013.74004829
 13358.13204273 15402.44892357]


In [14]:
lower_than = cat_obj_move < cat_obj
cat_obj[lower_than] = cat_obj_move[lower_than]
cat_pop[lower_than] = cat_pop_move[lower_than]

## Tikus bersembunyi ke dalam Sarang

In [15]:
haven_pop = generate_agent(lb, ub,size=(mice_pop.shape))
haven_obj = objective_function(haven_pop)
print('Populasi Sarang : \n',haven_pop)
print('\n')
print('Fungsi Objektif Populasi Sarang : \n',haven_obj)

Populasi Sarang : 
 [[ 95.66913664  88.62311973]
 [ -6.09712124  78.93973441]
 [ 36.15891559  26.2009285 ]
 [-14.74475232 -53.36985465]
 [ 46.17578152  12.03739656]
 [ 31.54908499  46.32400717]
 [-62.30682688  39.08543686]
 [-89.51622129  97.10219229]
 [-12.3393678   47.4541666 ]
 [ 87.49496279 -67.07157088]]


Fungsi Objektif Populasi Sarang : 
 [17006.64105518  6268.65655565  1993.95583072  3065.74910685
  2277.10171477  3141.25840356  5409.81204985 17441.98962282
  2404.15792511 12153.96413383]


In [16]:
def update_mice_escape(mice_pop, haven_pop, mice_obj, haven_obj):
  I = np.round(1 + np.random.rand(len(mice_pop), dm))
  r = np.random.rand()
  new_pop = mice_pop + r * (haven_pop - I * mice_pop) * np.sign(mice_obj - haven_obj)[:, np.newaxis]
  return new_pop

In [17]:
mice_pop_esc = update_mice_escape(mice_pop, haven_pop, mice_obj, haven_obj)
mice_obj_esc = objective_function(mice_pop_esc)
print('Populasi Tikus Kabur : \n',mice_pop_esc)
print('\n')
print('Fungsi Objektif Populasi Tikus Kabur : \n',mice_obj_esc)          

Populasi Tikus Kabur : 
 [[ -60.10165636 -121.2639689 ]
 [  75.45812954 -114.13725648]
 [ -25.0649117  -140.50883613]
 [  98.75082955   93.09590387]
 [  44.88285833  -50.85626901]
 [  32.27745376   80.36180336]
 [ 127.75498903   86.19205576]
 [ 151.50981186   33.95269539]
 [ -12.96990109   47.97129729]
 [-331.21007866   88.52015809]]


Fungsi Objektif Populasi Tikus Kabur : 
 [ 18317.15924969  18721.24263056  20370.98282755  18418.57365436
   4600.83106915   7499.85346066  23750.40769968  24108.00861545
   2469.46369827 117535.93459381]


In [18]:
lower_than = mice_obj_esc < mice_obj
mice_obj[lower_than] = mice_obj_esc[lower_than]
mice_pop[lower_than] = mice_pop_esc[lower_than]

## Populasi Update

In [19]:
agent = np.concatenate([mice_pop, cat_pop], axis=0)
print('Populasi Update : \n',agent)

Populasi Update : 
 [[ 16.69093583 -11.91765846]
 [ 23.61220172 -18.95328562]
 [  5.11748842 -39.06503963]
 [ 42.79926273  20.89054979]
 [ -0.54472734  66.22596539]
 [ 57.86910156 -37.38912793]
 [ 34.05745281  62.96922108]
 [ 32.68770462  65.08442085]
 [-12.96990109  47.97129729]
 [-83.58758234  11.8158417 ]
 [-55.63205153  65.34690606]
 [ 89.18573847  -8.64031425]
 [-86.43250773 -23.7707804 ]
 [ 60.86936001 -71.32218467]
 [ 55.78264713 -78.2062056 ]
 [ 88.20974153 -52.16267925]
 [-83.00927447 -72.123492  ]
 [-92.7668201  -58.37856744]
 [-78.66500518 -84.67555139]
 [ 84.17645204  91.19634777]]


In [20]:
new_obj = np.concatenate([mice_obj, cat_obj], axis=0)
new_obj
print('Fungsi Objektif Populasi Update : \n',new_obj)

Fungsi Objektif Populasi Update : 
 [  420.61792202   916.76310571  1552.26600883  2268.19196059
  4386.1752202   4746.77980201  5125.0328949   5304.4678711
  2469.46369827  7126.4980359   7365.14328912  8028.75097647
  8035.62839354  8791.93301459  9227.91431494 10501.90360856
 12092.33774572 12013.74004829 13358.13204273 15402.44892357]


## Pengulangan Langkah CMBO

In [21]:
iter = 1
while iter < max_iter:
  # Menghitung nilai fungsi Objektif
  F_obj = objective_function(agent)
            
  # Mengurutkan Populasi berdasarkan F_obj
  sorted_index = F_obj.argsort()
  F_obj = F_obj[sorted_index]
  agent_ori = agent.copy()
  agent = agent[sorted_index]

  # Membagi Populasi awal menjadi 2 Populasi (Tikus dan Kucing)
  upper_half = slice(gen_mice)
  lower_half = slice(gen_mice, len(agent))

  # Tikus
  mice_pop = agent[upper_half]
  mice_obj = F_obj[upper_half]

  # Kucing
  cat_pop = agent[lower_half]
  cat_obj = F_obj[lower_half]

  # Perubahan posisi Kucing
  cat_pop_move = update_cat_movement(cat_pop, mice_pop)
  cat_obj_move = objective_function(cat_pop_move)
  lower_than = cat_obj_move < cat_obj
  cat_obj[lower_than] = cat_obj_move[lower_than]
  cat_pop[lower_than] = cat_pop_move[lower_than]

  # Membentuk sarang
  haven_pop = generate_agent(lb, ub,size=(mice_pop.shape))
  haven_obj = objective_function(haven_pop)

  # Perubahan posisi tikus
  mice_pop_esc = update_mice_escape(mice_pop, haven_pop, mice_obj, haven_obj)
  mice_obj_esc = objective_function(mice_pop_esc)
            
  lower_than = mice_obj_esc < mice_obj
  mice_obj[lower_than] = mice_obj_esc[lower_than]
  mice_pop[lower_than] = mice_pop_esc[lower_than]
            
  # Agent Baru ( Gabungkan kedua perubahan antara populasi tikus dan kucing)
  new_obj = np.concatenate([mice_obj, cat_obj], axis=0)
  agent = np.concatenate([mice_pop, cat_pop], axis=0)
  
  iter+=1
  print()
  print('Iterasi ke-', iter)
  print('Populasi Tikus : \n', mice_pop)
  print('\n')
  print('Populasi Kucing: \n',cat_pop)
  print('\n')
  print('Fungsi Objektif: \n', new_obj)


Iterasi ke- 2
Populasi Tikus : 
 [[ 17.57895733  -2.95126256]
 [ 18.89328422 -11.33738357]
 [  5.11748842 -39.06503963]
 [ 42.79926273  20.89054979]
 [-12.96990109  47.97129729]
 [ -0.54472734  66.22596539]
 [ 57.86910156 -37.38912793]
 [ 34.05745281  62.96922108]
 [ 12.1394246   46.90936129]
 [-56.68398775   6.59665126]]


Populasi Kucing: 
 [[-41.36826046  44.22377318]
 [ 74.04209756 -11.1673673 ]
 [-57.4359456  -25.48221027]
 [ 52.84280814 -58.09466467]
 [ 56.04485372 -63.24844351]
 [ 73.31140943 -50.30607389]
 [-73.83626957 -55.74080587]
 [-65.30496339 -58.69456999]
 [-51.62074099 -78.73302441]
 [ 80.87038385  75.03689643]]


Fungsi Objektif: 
 [  317.7296916    485.49245463  1552.26600883  2268.19196059
  2469.46369827  4386.1752202   4746.77980201  5125.0328949
  2347.85380601  3256.59027486  3667.07508801  5606.94230275
  3948.23088745  6167.35243509  7141.39123456  7905.26382315
  8558.83214335  7709.79079005  8863.59003236 12170.55481133]

Iterasi ke- 3
Populasi Tikus : 
 [[ 

## Hasil Akhir Metode CMBO

In [22]:
# Solusi optimal
print('Solusi Optimal : \n', agent[0])
print('Fungsi Objektif: \n', new_obj[0])

Solusi Optimal : 
 [5.61658497e-13 1.23202294e-12]
Fungsi Objektif: 
 1.8333407948248373e-24
